
# GitLab CI Docker Image
image: node:8

cache:
  paths:
    - node_modules/

stages:
  - clear
  - test
  - build
  - release

# Configuration
# variables:
#   AWS_ACCESS_KEY_ID: "" # Should have access to both S3/EB
#   AWS_SECRET_ACCESS_KEY: ""
#   AWS_DEFAULT_REGION: "us-east-1" # Or, wherever you are
#   EB_APP_NAME: "" # ElasticBeanstalk Application Name
#   EB_APP_ENV: "" # ElasticBeanstalk Application Environment
#   S3_BUCKET: "" # S3 bucket for ElasticBeanstalk
#   S3_KEY: "" # S3 folder to upload built app

clear:
  stage: clear
  script:
    - npm prune
  # artifacts:
  #   paths:
  #     - node_modules/
  #     - dist/
  # tags:
  #   - nodejs-app

# Job: Test
# Run tests against our application
# If this fails, we do not release
test:
  stage: test
  script:
    - npm run cover
    - npm run check-coverage
  # tags:
  #   - nodejs-app

build:
  stage: build
  script:
    - npm run build
    

release:
  stage: release
  script:
    - npm run report-coverage
    - npm run semantic-release
    

# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new EB version and switches to that version
# deploy:
#   stage: deploy 
#   script:
#     - ./bin/deploy
#   tags:
#     - nodejs-app